# Generated by Django 3.0.3 on 2021-11-18 09:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=191)),
                ('price', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.filepath)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='gilan',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
