# Generated by Django 3.0.3 on 2021-11-18 10:11

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211118_0900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='client_type',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='datetime',
            field=models.DateTimeField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='doctor',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='iin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tel_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=api.models.filepath),
        ),
    ]
