# Generated by Django 3.0.3 on 2021-11-26 06:04

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211118_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(blank=True, max_length=2000, null=True, upload_to=api.models.filepath),
        ),
    ]
