# Generated by Django 3.0.3 on 2021-12-02 05:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211126_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.FileField(null=True, upload_to=api.models.filepath),
        ),
        migrations.AlterField(
            model_name='item',
            name='link',
            field=models.TextField(max_length=2500, null=True),
        ),
    ]
